name: Deploy

on:
  push:
    branches:
      - master

env:
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  PATH_TO_PROJECT: "C:/Users/rosel/myPROJECTS/myTGassistant"

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Install OpenSSH Client
        shell: powershell
        run: |
          Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.24.1"

      - name: Build
        run: go build -o app.exe

      - name: Prepare SSH
        shell: powershell
        run: |
          New-Item -ItemType Directory -Path "$env:SERVER_USER\.ssh" -Force | Out-Null

          ssh-keyscan -H $env:SERVER_IP >> "$env:SERVER_USER\.ssh\known_hosts"

          Write-Host "Added host key:"
          Get-Content "$env:SERVER_USER\.ssh\known_hosts" | Select-Object -Last 1

      - name: Deploy to Server
        shell: powershell
        run: |
          $env:SSH_KEY | Out-File -FilePath deploy_key -Encoding ASCII
          icacls.exe deploy_key /reset
          icacls.exe deploy_key /grant:r "$env:SERVER_USER:(R)"

          ssh -i deploy_key `
              -o ConnectTimeout=30 `
              $env:SERVER_USER@$env:SERVER_IP @"
            cd "$env:PATH_TO_PROJECT"
            git pull origin master
            .\deploy.ps1
          "@

          if ($LASTEXITCODE -ne 0) {
              Write-Host "##[error] Deployment failed!"
              exit 1
          }
          Write-Host "Deployment successful!"
