name: Deploy

on:
  push:
    branches: [master]

env:
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  PROJECT_DIR: "/home/rosel/Gelya/my_PROJECTS/tgAssistant" 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.24.1"

      - name: Build binary
        run: go build -o app

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
          
      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/deploy_key -T $SERVER_USER@$SERVER_IP "echo 'SSH connection successful!'"

      - name: Deploy to server
        run: |
          scp -i ~/.ssh/deploy_key ./app $SERVER_USER@$SERVER_IP:$PROJECT_DIR/app_new
          ssh -i ~/.ssh/deploy_key $SERVER_USER@$SERVER_IP "cd $PROJECT_DIR && chmod +x deploy.sh && ./deploy.sh"