name: Deploy

on:
  push:
    branches: [master]

env:
  SERVER_IP: ${{ secrets.SERVER_IP }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  PROJECT_DIR: "/home/rosel/Gelya/my_PROJECTS/tgAssistant" 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.24.1"

      - name: Build binary
        run: go build -o app

      - name: Setup SSH
        run: |
          set -x #Logging
          echo "Making dir"
          mkdir -p ~/.ssh
          echo "Writing deploy_key"
          echo "$SSH_KEY" > ~/.ssh/deploy_key
          echo "Adding chmod rules"
          chmod 600 ~/.ssh/deploy_key
          echo "Adding IP to known_hosts"
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
          
      - name: Test SSH connection
        run: |
          set -x
          echo "Trying to connect"
          ssh -i ~/.ssh/deploy_key -T $SERVER_USER@$SERVER_IP "echo 'SSH connection successful!'"

      - name: Deploy to server
        run: |
          set -x
          echo "Deploy to server: command 1"
          scp -o BatchMode=yes -i ~/.ssh/deploy_key ./app $SERVER_USER@$SERVER_IP:$PROJECT_DIR/app_new
          echo "Deploy to server: command 2"
          ssh -o BatchMode=yes -i ~/.ssh/deploy_key $SERVER_USER@$SERVER_IP "cd $PROJECT_DIR && chmod +x deploy.sh && ./deploy.sh"